/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        },
      },
    },
  },
  plugins: [],
  // Ensure CSS is not purged in production
  safelist: [
    'btn-primary',
    'btn-secondary',
    'input-field',
    'card',
    'text-primary-600',
    'hover:text-primary-700',
    'text-gray-900',
    'text-gray-600',
    'text-gray-500',
    'text-red-600',
    'bg-gray-50',
    'bg-white',
    'border',
    'rounded',
    'rounded-lg',
    'shadow-md',
    'p-6',
    'py-2',
    'px-4',
    'py-8',
    'mb-4',
    'mb-2',
    'space-y-4',
    'space-y-6',
    'space-x-4',
    'flex',
    'items-center',
    'justify-between',
    'items-start',
    'flex-1',
    'min-w-0',
    'flex-shrink-0',
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'gap-4',
    'text-sm',
    'text-lg',
    'text-2xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'h-12',
    'w-12',
    'h-96',
    'w-full',
    'max-w-full',
    'h-auto',
    'hidden',
    'block',
    'text-center',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'transition-colors',
    'duration-200',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-primary-500',
    'focus:border-transparent',
    'hover:bg-primary-700',
    'hover:bg-gray-300',
    'hover:text-primary-700',
  ],
} 